document.addEventListener('DOMContentLoaded', () => {
    const grid = document.getElementById('results-grid');
    const refreshBtn = document.getElementById('refresh-btn');
    const queryForm = document.getElementById('query-form');
    const queryInput = document.getElementById('query-input');

    const fetchData = async () => {
        try {
            grid.innerHTML = `
                <div class="loading-state">
                    <div class="spinner"></div>
                    <p>Loading insights...</p>
                </div>
            `;
            
            // Fetch the JSON generated by engine.py
            // Add a cache-busting timestamp to prevent browser caching
            const response = await fetch(`output_results.json?t=${new Date().getTime()}`);
            if (!response.ok) throw new Error('Failed to fetch data');
            
            const data = await response.json();
            renderDashboard(data);
        } catch (error) {
            grid.innerHTML = `
                <div class="error-state" style="grid-column: 1 / -1; margin: 40px;">
                    <h3>Failed to load data</h3>
                    <p>${error.message}</p>
                    <p>Make sure output_results.json exists and the local server is running.</p>
                </div>
            `;
        }
    };

    const createCard = (item) => {
        const card = document.createElement('div');
        card.className = 'result-card glass-panel';
        
        // Format confidence score
        const conf = (item.confidence_score * 100).toFixed(0);
        const confClass = conf > 80 ? '' : 'low';
        
        // Parse result
        let resultHtml = '';
        if (typeof item.result === 'string' && item.result.startsWith('Execution Error')) {
            resultHtml = `<div class="error-state">${item.result}</div>`;
        } else {
            try {
                const parsedResult = JSON.parse(item.result);
                if (parsedResult.length === 0) {
                    resultHtml = `<div class="sql-label">Result</div><p style="color: var(--text-secondary)">No rows returned.</p>`;
                } else if (parsedResult.length === 1 && Object.keys(parsedResult[0]).length === 1 && parsedResult[0][Object.keys(parsedResult[0])[0]] !== null) {
                    // Single value (e.g. Total Sales)
                    const val = parsedResult[0][Object.keys(parsedResult[0])[0]];
                    const formattedVal = typeof val === 'number' ? 
                        (val > 1000 ? val.toLocaleString() : parseFloat(val.toFixed(2))) : val;
                    resultHtml = `<div class="sql-label">Result</div><div class="single-value">${formattedVal}</div>`;
                } else {
                    // Table representation
                    const keys = Object.keys(parsedResult[0]);
                    
                    let thHtml = '';
                    keys.forEach(k => thHtml += `<th>${k.replace(/_/g, ' ')}</th>`);
                    
                    let trHtml = '';
                    parsedResult.forEach(row => {
                        let tdHtml = '';
                        keys.forEach(k => {
                            let val = row[k];
                            if (val === null) val = '-';
                            else if (typeof val === 'number') val = parseFloat(val.toFixed(2)).toLocaleString();
                            tdHtml += `<td>${val}</td>`;
                        });
                        trHtml += `<tr>${tdHtml}</tr>`;
                    });
                    
                    resultHtml = `
                        <div class="sql-label">Result</div>
                        <div class="data-table-container">
                            <table class="data-table">
                                <thead><tr>${thHtml}</tr></thead>
                                <tbody>${trHtml}</tbody>
                            </table>
                        </div>
                    `;
                }
            } catch (e) {
                // Fallback to raw string if not JSON
                resultHtml = `<div class="sql-container"><div class="sql-code">${item.result}</div></div>`;
            }
        }

        card.innerHTML = `
            <div class="card-header">
                <h3 class="query-title">"${item.query}"</h3>
                <span class="confidence-badge ${confClass}">${conf}% Conf</span>
            </div>
            <div class="sql-container">
                <span class="sql-label">Generated SQL</span>
                <div class="sql-code">${item.generated_logic}</div>
            </div>
            <div class="sql-container" style="margin-top: 12px; margin-bottom: 12px; background: rgba(0,0,0,0.15);">
                <span class="sql-label">Explanation</span>
                <div style="font-size: 13px; color: var(--text-secondary); line-height: 1.5;">${item.explanation || 'No explanation provided.'}</div>
            </div>
            ${resultHtml}
        `;
        
        return card;
    };

    const renderDashboard = (data) => {
        grid.innerHTML = '';
        data.forEach(item => {
            grid.appendChild(createCard(item));
        });
    };

    const submitQuery = async (e) => {
        e.preventDefault();
        const userPrompt = queryInput.value.trim();
        if (!userPrompt) return;
        
        const loadingCard = document.createElement('div');
        loadingCard.className = 'result-card glass-panel';
        loadingCard.innerHTML = `
            <div class="loading-state" style="padding: 20px;">
                <div class="spinner"></div>
                <p style="margin-top: 15px;">Generating SQL logic...</p>
            </div>
        `;
        grid.prepend(loadingCard);
        queryInput.value = '';

        try {
            const response = await fetch('/api/query', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ query: userPrompt })
            });
            if (!response.ok) throw new Error('Failed to query API');
            
            const data = await response.json();
            grid.removeChild(loadingCard);
            grid.prepend(createCard(data));
        } catch (error) {
            loadingCard.innerHTML = `
                <div class="error-state" style="padding: 20px;">
                    <h3>Failed to generate</h3>
                    <p>${error.message}</p>
                </div>
            `;
        }
    };

    if (queryForm) {
        queryForm.addEventListener('submit', submitQuery);
    }

    refreshBtn.addEventListener('click', fetchData);

    // Initial fetch
    fetchData();
});
